### ISSUE TITLE
Header looks broken on mobile

### ISSUE THREAD

**Issue by hebbet** [twbs/blog#148]
The header looks broken on mobile.

The Icon should be centered in my opinion.

Tested with Chrome on an Pixel 4 with Android 10.

![Screenshot_20200617-190036](https://user-images.githubusercontent.com/1423115/84927365-0496d700-b0cd-11ea-949a-d8449578c231.png)

**Comment by mdo** [comment]
Perhaps a caching issue? No problem on my end.

**Comment by hebbet** [comment]
Also happening in incognito and on a Pixel 3 that was never on the blog before.

**Comment by mdo** [comment]
This is what you should be seeing... All I did was replace the logo image most recently.

<img width="504" alt="Screen Shot 2020-06-17 at 1 24 05 PM" src="https://user-images.githubusercontent.com/98681/84946617-d5b53c80-b09d-11ea-99d4-58d0b38de7cf.png">

**Comment by patrickhlauke** [comment]
might be due to that tweaked B logo ... perhaps the modified SVG had some funkiness (`viewbox` and/or coordinates may have been muddled up from my rough modification in affinity).

for what it's worth i'm seeing this sort of thing on smaller viewports

> ![Uploading Annotation 2020-06-17 222824.png…]()

**Comment by mdo** [comment]
Maybe it's wanting a specific width in there? Right now I'm only setting height, and the viewbox is fine otherwise. Still strange this is happening here and not the main docs.

**Comment by XhmikosR** [comment]
I'm gonna add the width too, better be explicit with dimensions when possible.

**Comment by mdo** [comment]
Thinking after #153 and #154, this might be fixed. I still haven't seen any issues myself, so need help confirming.

**Comment by patrickhlauke** [comment]
confirming that this seems fixed now

> ![Annotation 2020-07-11 215939](https://user-images.githubusercontent.com/895831/87233717-d81b6580-c3c1-11ea-964b-c8ea6b8d81ab.png)
