### ISSUE TITLE
Feed Author Problem

### ISSUE THREAD

**Issue by ahmetcadirci25** [twbs/blog#158]
There is a problem in the feed author section.

https://blog.getbootstrap.com/feed.xml

```
<author>
<name>{"twitter"=>"getbootstrap"}</name>
</author>
```

![Ekran Alıntısı](https://user-images.githubusercontent.com/9280397/89562040-0f92fb80-d822-11ea-8eb6-f064b31eeeb8.PNG)

**Comment by mdo** [comment]
Oh that's no good. Will look into soon.

**Comment by XhmikosR** [comment]
@ahmetcadirci25 what are you using to view the feed? Since the jekyll-feed gem is the latest, it might be a configuration error on our side or a bug somewhere even in the tool you are using.

**Comment by MartijnCuppens** [comment]
@XhmikosR, the bug is visible in the xml he's linking to

**Comment by XhmikosR** [comment]
Well, the raw XML does have this, but the rendered feed looks fine here with the Livemarks extension installed on Firefox.

![Screen Shot 2020-09-15 at 12 43 31-fullpage](https://user-images.githubusercontent.com/349621/93194842-344b8e80-f751-11ea-948a-2c43d43b16ae.png)

**Comment by patrickhlauke** [comment]
only because livemarks doesn't show the author. otherwise it would show that unprocessed moustache template code or whatever that is.

**Comment by XhmikosR** [comment]
I'm gonna take a stab at configuring the authors differently later, but it'd be nice if I could reproduce the issue without having to look at the XML source.

**Comment by patrickhlauke** [comment]
it depends on the RSS/Atom reader you use (and whether or not it drops/hides author field, or omits nonsensical characters/fields. this shows up in feedly, for instance.

> ![Screenshot of Feedly displaying the Bootstrap blog with the author showing the nonsensical/unprocessed instructions](https://user-images.githubusercontent.com/895831/93210925-690f1400-f758-11ea-8c3a-b2f948c0baaf.png)

**Comment by XhmikosR** [comment]
Please try https://deploy-preview-162--bootstrapblog.netlify.app/

There's an issue with multiple authors (the first one will be used) and secondly I'm not sure the default "Mark Otto, Jacob Thornton, and Bootstrap contributors" makes sense in `ld+json`. But let's discuss these things in the PR.

**Comment by patrickhlauke** [comment]
https://deploy-preview-162--bootstrapblog.netlify.app/feed.xml looks correct now
