### ISSUE TITLE
The bug on .row>* {}

### ISSUE THREAD

**Issue by vardhan1122** [twbs/blog#222]
Hi Good Afternoon,

.row>* {
    flex-shrink: 0;
    width: 100%;
    max-width: 100%;
    padding-right: calc(var(--bs-gutter-x)/ 2);
    padding-left: calc(var(--bs-gutter-x)/ 2);
    margin-top: var(--bs-gutter-y);
}

you this one is added in recent updations, because of this inline tag elements doesn't work properly like, button , please guide me how to get inline tag elements.

sincerly thanks
vardhan

**Comment by mdo** [comment]
Wrong repo, and grid columns are the only supported children elements of rows.
