### ISSUE TITLE
5.1.1 is broken

### ISSUE THREAD

**Issue by anders16000** [twbs/blog#241]
both downloaded zip fails and 
link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"

integrity fail.

**Comment by XhmikosR** [comment]
This is the wrong repo and the info you provided is poor.
