### ISSUE TITLE
v5.3.0-alpha1 YouTube video unavailable

### ISSUE THREAD

**Issue by julien-deramond** [twbs/blog#332]
Don't know exactly why but [this video](https://www.youtube.com/watch?v=zcgxBHBsl-4) is not unavailable in my case 🤷 

<img width="316" alt="Screenshot 2022-12-26 at 21 15 08" src="https://user-images.githubusercontent.com/17381666/209580910-a5c26bc7-21ca-4450-b18e-9c4bc583fb8c.png">

**Comment by XhmikosR** [comment]
Yeah, they must block it in Europe because I hit it too. @mdo removed it for the time being.

**Comment by hebbet** [comment]
Blocked in many countries.

https://watannetwork.com/tools/blocked/#url=zcgxBHBsl-4

XhmikosR ***@***.***> schrieb am Di., 27. Dez. 2022, 07:03:
