### ISSUE TITLE
Simpler footer with no social buttons, fewer links

### ISSUE THREAD

**Issue by adammacias** [twbs/blog#37]
In docs [was removed](https://github.com/twbs/bootstrap/commit/c9c9c614a90639e36b34ae44cf4001c01ba9146b) the social buttons, maybe we can do it here too, what you think guys?

**Comment by zdroid** [comment]
This has been solved and should be closed.

cc @cvrebert @XhmikosR

**Comment by MartijnCuppens** [comment]
Indeed, thanks @zdroid
