### ISSUE TITLE
Theme the blog like the site

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/blog#86]
The blog template looks a bit too clean. Maybe we should theme it like our main site? This will make look everything more coherent. 

Thoughts @mdo?

**Comment by MartijnCuppens** [comment]
@ashmaroli, that's indeed a possibility, but we're probably going to switch to Hugo for our docs. I wonder if we can just merge the blog in the docs repo 🤔

**Comment by XhmikosR** [comment]
Nah, we better move things out of the main repo than add more.

**Comment by ashmaroli** [comment]
> we're probably going to switch to Hugo for our docs.

I'm biased towards Jekyll. So, I can't help but wonder, is there a compelling reason to consider switching to Hugo..?

**Comment by XhmikosR** [comment]
No need to get out of topic here, but the gist is that Jekyll is super slow.

**Comment by XhmikosR** [comment]
@MartijnCuppens I think we can close this now?

**Comment by MartijnCuppens** [comment]
yup
